# Generated by Django 3.1.1 on 2020-09-20 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('image', models.ImageField(upload_to='images/category_img')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('primary_image', models.ImageField(upload_to='images/food_image')),
                ('secondary_image_1', models.ImageField(upload_to='images/food_image')),
                ('secondary_image_2', models.ImageField(upload_to='images/food_image')),
                ('secondary_image_3', models.ImageField(upload_to='images/food_image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.category')),
            ],
        ),
    ]
