# Generated by Django 3.1.1 on 2020-09-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_auto_20200920_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='food',
            name='unit_serving',
            field=models.CharField(choices=[('Plate', 'Plate'), ('Pcs', 'Pcs'), ('Dozens', 'Dozens')], default='Plate', max_length=50),
        ),
    ]
