# Generated by Django 3.1.1 on 2020-09-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_auto_20200923_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='isPopular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='unit_serving',
            field=models.CharField(choices=[('Plate', 'Plate'), ('Piece', 'Piece'), ('Dozens', 'Dozens')], default='Plate', max_length=50),
        ),
    ]
