# Generated by Django 3.1.1 on 2020-09-24 04:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 9, 24, 4, 51, 53, 555786, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='order_amount',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
