# Generated by Django 3.1.1 on 2020-09-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_auto_20200924_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='address_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
